#Plugins
systemProp.kotlinVersion=2.4.20-RC
systemProp.kspVersion=2.3.11
systemProp.kiluaRpcVersion=0.0.46-SNAPSHOT
#Dependencies
systemProp.kvisionVersion=9.7.0-RC
ktorVersion=3.5.2
hikariVersion=3.2.0
commonsCodecVersion=1.10
jdbcNamedParametersVersion=1.1
exposedVersion=0.17.14
logbackVersion=1.6.3
h2Version=1.4.197
pgsqlVersion=42.2.2
kweryVersion=0.17

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
