#Plugins
systemProp.kotlinVersion=2.4.0
systemProp.kspVersion=2.3.9
systemProp.kiluaRpcVersion=0.0.45-SNAPSHOT
systemProp.springBootVersion=4.1.0
#Dependencies
systemProp.kvisionVersion=9.6.0
coroutinesVersion=1.11.0
r2dbcPostgresqlVersion=1.1.1.RELEASE
r2dbcH2Version=1.0.0.RELEASE
e4kVersion=0.9.0

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
