#Plugins
systemProp.kotlinVersion=2.4.20-RC
systemProp.kspVersion=2.3.11
systemProp.kiluaRpcVersion=0.0.46-SNAPSHOT
systemProp.springBootVersion=4.1.0
#Dependencies
systemProp.kvisionVersion=9.7.0-RC
coroutinesVersion=1.11.0
r2dbcPostgresqlVersion=1.1.1.RELEASE
r2dbcH2Version=1.0.0.RELEASE
e4kVersion=0.9.0

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
