#Plugins
systemProp.kotlinVersion=2.4.20
systemProp.kspVersion=2.3.12
systemProp.kiluaRpcVersion=0.0.46
#Dependencies
systemProp.kvisionVersion=9.7.0
ktorVersion=3.5.2
logbackVersion=1.6.3

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
