#Plugins
systemProp.kotlinVersion=2.4.0
systemProp.kspVersion=2.3.9
systemProp.kiluaRpcVersion=0.0.45-SNAPSHOT
#Dependencies
systemProp.kvisionVersion=9.6.0
ktorVersion=3.5.0
logbackVersion=1.5.34

org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
